improvement_quick:
	 ./improvement.pl ../biz/data/KN_SC_quick.txt ../biz/data/BIZ_SC_quick.txt > post_processed_data/improvement_KN_BIZ_SC_quick.txt
	 ./improvement.pl ../biz/data/KN_MDM_quick.txt ../biz/data/BIZ_MDM_quick.txt > post_processed_data/improvement_KN_BIZ_MDM_quick.txt
	 ./improvement.pl ../biz/data/KN_RPI_quick.txt ../biz/data/BIZ_RPI_quick.txt > post_processed_data/improvement_KN_BIZ_RPI_quick.txt
	 ./improvement.pl ../biz/data/KNHET_SC_INC_quick.txt ../biz/data/BIZHET_SC_INC_quick.txt > post_processed_data/improvement_KNHET_BIZHET_SC_INC_quick.txt
	 ./improvement.pl ../biz/data/KNHET_SC_DEC_quick.txt ../biz/data/BIZHET_SC_DEC_quick.txt > post_processed_data/improvement_KNHET_BIZHET_SC_DEC_quick.txt
	 ./improvement.pl ../biz/data/KNHET_MDM_INC_quick.txt ../biz/data/BIZHET_MDM_INC_quick.txt > post_processed_data/improvement_KNHET_BIZHET_MDM_INC_quick.txt
	 ./improvement.pl ../biz/data/KNHET_MDM_DEC_quick.txt ../biz/data/BIZHET_MDM_DEC_quick.txt > post_processed_data/improvement_KNHET_BIZHET_MDM_DEC_quick.txt
	 ./improvement.pl ../biz/data/KNHET_RPI_hetero_quick.txt ../biz/data/BIZHET_RPI_hetero_quick.txt > post_processed_data/improvement_KNHET_BIZHET_RPI_hetero_quick.txt
	 ./improvement.pl ../biz/data/KNHET_SC_INCA_quick.txt ../biz/data/BIZHET_SC_INCA_quick.txt > post_processed_data/improvement_KNHET_BIZHET_SC_INCA_quick.txt
	 ./improvement.pl ../biz/data/KNHET_SC_DECA_quick.txt ../biz/data/BIZHET_SC_DECA_quick.txt > post_processed_data/improvement_KNHET_BIZHET_SC_DECA_quick.txt
	 ./improvement.pl ../biz/data/KNHET_MDM_INCA_quick.txt ../biz/data/BIZHET_MDM_INCA_quick.txt > post_processed_data/improvement_KNHET_BIZHET_MDM_INCA_quick.txt
	 ./improvement.pl ../biz/data/KNHET_MDM_DECA_quick.txt ../biz/data/BIZHET_MDM_DECA_quick.txt > post_processed_data/improvement_KNHET_BIZHET_MDM_DECA_quick.txt
	 ./improvement.pl ../biz/data/KNHET_RPI_heteroA_quick.txt ../biz/data/BIZHET_RPI_heteroA_quick.txt > post_processed_data/improvement_KNHET_BIZHET_RPI_heteroA_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_SC_quick.txt ../biz/data/BIZUNK_SC_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_SC_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_MDM_quick.txt ../biz/data/BIZUNK_MDM_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_MDM_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_RPI_quick.txt ../biz/data/BIZUNK_RPI_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_RPI_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_SC_INC_quick.txt ../biz/data/BIZUNK_SC_INC_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_SC_INC_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_SC_DEC_quick.txt ../biz/data/BIZUNK_SC_DEC_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_SC_DEC_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_MDM_INC_quick.txt ../biz/data/BIZUNK_MDM_INC_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_MDM_INC_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_MDM_DEC_quick.txt ../biz/data/BIZUNK_MDM_DEC_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_MDM_DEC_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_RPI_hetero_quick.txt ../biz/data/BIZUNK_RPI_hetero_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_RPI_hetero_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_SC_INCA_quick.txt ../biz/data/BIZUNK_SC_INCA_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_SC_INCA_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_SC_DECA_quick.txt ../biz/data/BIZUNK_SC_DECA_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_SC_DECA_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_MDM_INCA_quick.txt ../biz/data/BIZUNK_MDM_INCA_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_MDM_INCA_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_MDM_DECA_quick.txt ../biz/data/BIZUNK_MDM_DECA_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_MDM_DECA_quick.txt
	 ./improvement.pl ../biz/data/KNUNK_RPI_heteroA_quick.txt ../biz/data/BIZUNK_RPI_heteroA_quick.txt > post_processed_data/improvement_KNUNK_BIZUNK_RPI_heteroA_quick.txt
improvement_final:
	 ./improvement.pl ../biz/data/KN_SC_final.txt ../biz/data/BIZ_SC_final.txt > post_processed_data/improvement_KN_BIZ_SC_final.txt
	 ./improvement.pl ../biz/data/KN_MDM_final.txt ../biz/data/BIZ_MDM_final.txt > post_processed_data/improvement_KN_BIZ_MDM_final.txt
	 ./improvement.pl ../biz/data/KN_RPI_final.txt ../biz/data/BIZ_RPI_final.txt > post_processed_data/improvement_KN_BIZ_RPI_final.txt
	 ./improvement.pl ../biz/data/KNHET_SC_INC_final.txt ../biz/data/BIZHET_SC_INC_final.txt > post_processed_data/improvement_KNHET_BIZHET_SC_INC_final.txt
	 ./improvement.pl ../biz/data/KNHET_SC_DEC_final.txt ../biz/data/BIZHET_SC_DEC_final.txt > post_processed_data/improvement_KNHET_BIZHET_SC_DEC_final.txt
	 ./improvement.pl ../biz/data/KNHET_MDM_INC_final.txt ../biz/data/BIZHET_MDM_INC_final.txt > post_processed_data/improvement_KNHET_BIZHET_MDM_INC_final.txt
	 ./improvement.pl ../biz/data/KNHET_MDM_DEC_final.txt ../biz/data/BIZHET_MDM_DEC_final.txt > post_processed_data/improvement_KNHET_BIZHET_MDM_DEC_final.txt
	 ./improvement.pl ../biz/data/KNHET_RPI_hetero_final.txt ../biz/data/BIZHET_RPI_hetero_final.txt > post_processed_data/improvement_KNHET_BIZHET_RPI_hetero_final.txt
	 ./improvement.pl ../biz/data/KNHET_SC_INCA_final.txt ../biz/data/BIZHET_SC_INCA_final.txt > post_processed_data/improvement_KNHET_BIZHET_SC_INCA_final.txt
	 ./improvement.pl ../biz/data/KNHET_SC_DECA_final.txt ../biz/data/BIZHET_SC_DECA_final.txt > post_processed_data/improvement_KNHET_BIZHET_SC_DECA_final.txt
	 ./improvement.pl ../biz/data/KNHET_MDM_INCA_final.txt ../biz/data/BIZHET_MDM_INCA_final.txt > post_processed_data/improvement_KNHET_BIZHET_MDM_INCA_final.txt
	 ./improvement.pl ../biz/data/KNHET_MDM_DECA_final.txt ../biz/data/BIZHET_MDM_DECA_final.txt > post_processed_data/improvement_KNHET_BIZHET_MDM_DECA_final.txt
	 ./improvement.pl ../biz/data/KNHET_RPI_heteroA_final.txt ../biz/data/BIZHET_RPI_heteroA_final.txt > post_processed_data/improvement_KNHET_BIZHET_RPI_heteroA_final.txt
	 ./improvement.pl ../biz/data/KNUNK_SC_final.txt ../biz/data/BIZUNK_SC_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_SC_final.txt
	 ./improvement.pl ../biz/data/KNUNK_MDM_final.txt ../biz/data/BIZUNK_MDM_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_MDM_final.txt
	 ./improvement.pl ../biz/data/KNUNK_RPI_final.txt ../biz/data/BIZUNK_RPI_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_RPI_final.txt
	 ./improvement.pl ../biz/data/KNUNK_SC_INC_final.txt ../biz/data/BIZUNK_SC_INC_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_SC_INC_final.txt
	 ./improvement.pl ../biz/data/KNUNK_SC_DEC_final.txt ../biz/data/BIZUNK_SC_DEC_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_SC_DEC_final.txt
	 ./improvement.pl ../biz/data/KNUNK_MDM_INC_final.txt ../biz/data/BIZUNK_MDM_INC_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_MDM_INC_final.txt
	 ./improvement.pl ../biz/data/KNUNK_MDM_DEC_final.txt ../biz/data/BIZUNK_MDM_DEC_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_MDM_DEC_final.txt
	 ./improvement.pl ../biz/data/KNUNK_RPI_hetero_final.txt ../biz/data/BIZUNK_RPI_hetero_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_RPI_hetero_final.txt
	 ./improvement.pl ../biz/data/KNUNK_SC_INCA_final.txt ../biz/data/BIZUNK_SC_INCA_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_SC_INCA_final.txt
	 ./improvement.pl ../biz/data/KNUNK_SC_DECA_final.txt ../biz/data/BIZUNK_SC_DECA_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_SC_DECA_final.txt
	 ./improvement.pl ../biz/data/KNUNK_MDM_INCA_final.txt ../biz/data/BIZUNK_MDM_INCA_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_MDM_INCA_final.txt
	 ./improvement.pl ../biz/data/KNUNK_MDM_DECA_final.txt ../biz/data/BIZUNK_MDM_DECA_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_MDM_DECA_final.txt
	 ./improvement.pl ../biz/data/KNUNK_RPI_heteroA_final.txt ../biz/data/BIZUNK_RPI_heteroA_final.txt > post_processed_data/improvement_KNUNK_BIZUNK_RPI_heteroA_final.txt

